### ISSUE TITLE
Set isExpand into true from ShadInput shows AssertError

### ISSUE THREAD

**Issue by moshOntong-IT** [nank1ro/flutter-shadcn-ui#104]
### Steps to reproduce

``` dart
 ShadInput(
            expands: true,
            maxLength: 300,
            controller: textEditingController,
            placeholder: const Text('Add your announcement here...'),
            decoration: const ShadDecoration(
              merge: false,
              border: ShadBorder.none,
              focusedBorder: ShadBorder.none,
            ),
          )
 ```

### Expected results

It should not appear the error

### Actual results

> Exception has occurred.
_AssertionError ('package:flutter/src/widgets/editable_text.dart': Failed assertion: line 886 pos 10: '!expands || (maxLines == null && minLines == null)': minLines and maxLines must be null when expands is true.)

### Platform

Windows

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moshOntong-IT** [comment]
```
  int? maxLines = 1,
  int? minLines,
 ```
 
 The maxlines has default value that is why the Assert Error triggered.

**Comment by nank1ro** [comment]
This is the same behavior of TextField, I don't think we need to change it. Just use
```dart
expands: true,
maxLines: null,
```

**Comment by moshOntong-IT** [comment]
> This is the same behavior of TextField, I don't think we need to change it. Just use
> 
> ```dart
> 
> expands: true,
> 
> maxLines: null,
> 
> ```
> 
> 

I think it should be, the user experience of programmer must be improve. What if there is newbie programmer and dont know yet how to read the problem. Technically, in future you will receive more github issue with the same topic. The option could be : add in the Description of Assert that you need to set the maxLine into null

**Comment by nank1ro** [comment]
It's already in the description of the assert
> minLines and maxLines must be null when expands is true

The default it's good because it's the most common use case, where the user has just one max line.
