### ISSUE TITLE
How to get ShadInput validation error.

### ISSUE THREAD

**Issue by yusuphwickama** [nank1ro/flutter-shadcn-ui#106]
Hello, 

I have this field with a custom validator. How can I access the error message from the validator and display it in my custom Text widget?

```dart
ShadInputFormField(
  id: 'account_number',
  enableSuggestions: false,
  error: Padding(
    padding: EdgeInsets.symmetric(horizontal: 6.w),
    child: Text(errorText, style: theme.textTheme.small.copyWith(color: theme.colorScheme.destructive)),
  ),
  label: Padding(
    padding: EdgeInsets.symmetric(horizontal: 6.w),
    child: Text('Account Number', style: theme.textTheme.small.copyWith(fontWeight: FontWeight.bold)),
  ),
  placeholder: Text('$providerType account number'),
  validator: (v) {
    if (v.length < 13) {
      return 'Account must be 13 characters.';
    }
    return null;
  },
),
```
I  want to assign it to `errorText`

**Comment by nank1ro** [comment]
Will add it, meanwhile use setState errorText in the validator

**Comment by nank1ro** [comment]
If you're just changing the text style and padding, consider using errorStyle and errorPadding passing the decoration

**Comment by yusuphwickama** [comment]
> If you're just changing the text style and padding, consider using errorStyle and errorPadding passing the decoration

Thanks, I did not notice this parameter.

**Comment by yusuphwickama** [comment]
> Will add it, meanwhile use setState errorText in the validator

I have multiple fields, this is just one of them so this approach might quickly get complicated.

**Comment by nank1ro** [comment]
> > Will add it, meanwhile use setState errorText in the validator
> 
> I have multiple fields, this is just one of them so this approach might quickly get complicated.

You can change it from the theme level to all form fields:
```dart
ShadThemeData(
    decoration: ShadDecoration(
        labelStyle: TextStyle(color: Colors.blue),
        errorStyle: TextStyle(color: Colors.orange),
        errorPadding: const EdgeInsets.symmetric(horizontal: 6),
        labelPadding: const EdgeInsets.symmetric(horizontal: 6),
  ),
),
```

or just for the Input fields
```dart
ShadThemeData(
  inputTheme: ShadInputTheme(
    decoration: ShadDecoration(
      labelStyle: TextStyle(color: Colors.blue),
      errorStyle: TextStyle(color: Colors.orange),
      errorPadding: const EdgeInsets.symmetric(horizontal: 6),
      labelPadding: const EdgeInsets.symmetric(horizontal: 6),
    ),
  ),
)
```

or for each single field widget passing the `decoration`

**Comment by yusuphwickama** [comment]
Thanks
