### ISSUE TITLE
ShadPopover doesn't work correctly with BackdropFilter

### ISSUE THREAD

**Issue by Jakemangan** [nank1ro/flutter-shadcn-ui#109]
### Steps to reproduce

I want to be able to blur/darken the background when a ShadPopover is open. However if I try to add a BackdropFilter to blur the background the container of the popover itself is blurred.

Please either add a way to blur/darken the background behind the popover or fix this bug so we can add the blur/darken ourselves.

As you can see from the image it almost works as some of the elements of the popover are unblurred but the container itself also gets blurred.

```
ShadPopover(
                    controller: popoverController,
                    popover: (context) => BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 3, sigmaY: 3),
                      child: SizedBox(
                        height: 200,
                        width: 200,
                        child: Column(
                          children: [
                            Text("Menu 1"),
                            Text("Menu 2"),
                            Text("Menu 3"),
                          ],
                        ),
                      ),
                    ),
                    child: OutlinedButton(
                      child: Text("Press"),
                      onPressed: () {
                        popoverController.show();
                      },
                    ),
                  )
```

<img width="390" alt="image" src="https://github.com/user-attachments/assets/754b9f98-3f6a-429d-b03b-bf045b14a4d6">

### Expected results

The background should be blurred while the popover should be unblurred.

### Actual results

The background and the popover container are blurred

### Platform

iOS

### Code sample

<details open><summary>Code sample</summary>

```dart
ShadPopover(
                    controller: popoverController,
                    popover: (context) => BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 3, sigmaY: 3),
                      child: SizedBox(
                        height: 200,
                        width: 200,
                        child: Column(
                          children: [
                            Text("Menu 1"),
                            Text("Menu 2"),
                            Text("Menu 3"),
                          ],
                        ),
                      ),
                    ),
                    child: OutlinedButton(
                      child: Text("Press"),
                      onPressed: () {
                        popoverController.show();
                      },
                    ),
                  )
```

</details>

### Screenshots or Video

None

### Logs

None

### Flutter Doctor output

N/A

**Comment by nank1ro** [comment]
Do you like this result?

<img width="430" alt="Screenshot 2024-07-25 at 17 24 17" src="https://github.com/user-attachments/assets/a160c845-8e60-4ff2-9dcf-0b152eb29b63">

**Comment by Jakemangan** [comment]
That looks perfect, is that possible with how the code is at the moment?

**Comment by Jakemangan** [comment]
Forgot to mention in the OP that I may have just been using the widget incorrectly.

**Comment by nank1ro** [comment]
No I'm going to release a new version soon, adding a new parameter `filter` to the Popover and Select components
