### ISSUE TITLE
`backgroundColor` is ignored by `ShadInputTheme`

### ISSUE THREAD

**Issue by joshmossas** [nank1ro/flutter-shadcn-ui#111]
### Steps to reproduce

1. Create a `ShadApp` with a custom `ShadInputTheme` that has the background color changed

I've created a minimal reproduction here:
https://github.com/joshmossas/shadcn_reproduction

### Expected results

The background color of `ShadInput` should match the backgroundColor set in `ShadInputTheme`

### Actual results

The background color does not change. Additionally there is no parameter on `ShadInput` to manually change the background color.

### Platform

Linux, Android, Web

### Code sample

A minimal reproduction can be found here
https://github.com/joshmossas/shadcn_reproduction

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/9c348e3a-0ac8-47ca-9ec1-db29f80f8eb8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on Pop!_OS 22.04 LTS 6.9.3-76060903-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by joshmossas** [comment]
Okay so I just figured out that I can set the background by overriding the `decoration` property

```dart
ShadThemeData(
  inputTheme: ShadInputTheme(
    decoration: ShadDecoration(
      color: Colors.white,
    ),
  ),
);
```

So then what is the purpose of the `backgroundColor` property? Should it just be ignored?

**Comment by nank1ro** [comment]
The backgroundColor parameter is a typo, I will remove it in the next version.
It's correct how you did with the decoration.
Thanks for the nice issue ✌️
