### ISSUE TITLE
The constraints parameter is ignored in the ShadSheet widget

### ISSUE THREAD

**Issue by patricknicolosi** [nank1ro/flutter-shadcn-ui#115]
### Steps to reproduce

Show a ShadSheet and sets a value to the contraints parameter

### Expected results

ShadSheet must take the constraints you set

### Actual results

ShadSheet does not set constraints

### Platform

Windows

### Code sample

```dart
...
  @override
  Widget build(BuildContext context) {
    return ShadSheet(
      constraints: BoxConstraints(minHeight:    1200),
      actionsAxis: Axis.horizontal,
      title: const Text('Modifica utente'),
      description: const Text(
              "Modifica tutte le informazioni e salvale per renderle effettive"),
      padding: const EdgeInsets.all(20),
      child: SizedBox(
        height: MediaQuery.of(context).size.height - 250,
        width: MediaQuery.of(context).size.width,
        child: Row(
          children: [
            Expanded(
              child: Column(
                children: [
                  Spacer(),
                  ShadInputFormField(
                    maxLines: 3,
                    minLines: 3,
                    label: const Text("Nota pubblica"),
                    onChanged: (_) {
                      _user.publicNote = _;
                    },
                    placeholder: const Text("Inserisci nota pubblica"),
                  ),
                  const SizedBox(height: 5),
                  ShadInputFormField(
                    maxLines: 3,
                    minLines: 3,
                    label: const Text("Nota privata"),
                    onChanged: (_) {
                      _user.privateNote = _;
                    },
                    placeholder: const Text("Inserisci nota privata"),
                  ),
                ],
              ),
            ),
            const VerticalDivider(width: 40),
            Expanded(
              flex: 4,
              child: Material(
                  color: Colors.transparent,
                  child: _navigationBarDestinations[_currentIndex].screen),
            ),
          ],
        ),
      ),
      actions: [
        ShadButton(
          child: const Text('Salva'),
          onPressed: () async {  },
        ),
      ],
    );
  }
```

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Versione 10.0.22631.3880], locale it-IT)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
[!] Android Studio (not installed)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.

**Comment by nank1ro** [comment]
What are you trying to achieve? Can you a screenshot?
In which side are your opening the sheet?

**Comment by patricknicolosi** [comment]
<img width="959" alt="Immagine 2024-07-31 115320" src="https://github.com/user-attachments/assets/c906cdfa-8320-46ca-8bfc-b678c48a2a86">
I open the sheet from the bottom and I would like this sheet to be heighter
