### ISSUE TITLE
Support for listening ShadResizablePanel resize event

### ISSUE THREAD

**Issue by pierremrtn** [nank1ro/flutter-shadcn-ui#124]
I would like to build a menu that collapse when size hit a minimal threshold.
Is it possible already ? Ideally I would have liked a `onResized(size)` callback on the ShadResizablePanel widget.

**Comment by nank1ro** [comment]
You can pass a `controller` to the ResizableGroup and listen to changes.
If you are interested on all panels check the `panelsInfo`, if you are interested in a specific one use `getPanelInfo(index)` method.
Let me know if you need further help

**Comment by nank1ro** [comment]
Closing this for now cause seems solved, feel free to comment if you don't agree
