### ISSUE TITLE
Getting unexpected null value when using anything that gets BuildContext.

### ISSUE THREAD

**Issue by danneillouven** [nank1ro/flutter-shadcn-ui#125]
I'm using shadcn_ui ^0.8.0 and flutter 3.22.3. I'm trying to use dialog or popover but I get unexpected null value when a button i clicked.

Code Sample:
`// ignore_for_file: avoid_print

import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    final profile = [
      (title: 'Name', value: 'Alexandru'),
      (title: 'Username', value: 'nank1ro'),
    ];
    return ShadApp.material(
      debugShowCheckedModeBanner: false,
      home: Center(
        child: ShadButton.outline(
          width: 125.0,
          height: 40.0,
          child: const Text(
            'Click me!',
            style: TextStyle(
              color: Colors.black,
            ),
          ),
          onPressed: () {
            print("Clicked!");
            ShadToaster.of(context).show(
              ShadToast(
                title: const Text('Scheduled: Catch up'),
                description: const Text('Friday, February 10, 2023 at 5:57 PM'),
                action: ShadButton.outline(
                  child: const Text('Undo'),
                  onPressed: () => ShadToaster.of(context).hide(),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
`

Console:
`══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 586:18  nullCheck
packages/shadcn_ui/src/components/toast.dart 28:28                                of
packages/shadcn_test/main.dart 38:25                                              <fn>
packages/shadcn_ui/src/components/button.dart 628:12                              onTap
packages/flutter/src/gestures/recognizer.dart 344:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 696:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 425:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#1d8f3
════════════════════════════════════════════════════════════════════════════════════════════════════

`

**Comment by nank1ro** [comment]
You’re using the BuildContext above ShadApp.
Put the widgets in another class, or wrap your home widget into a Builder
