### ISSUE TITLE
Option to hide the close button in a Sheet

### ISSUE THREAD

**Issue by jonsaw** [nank1ro/flutter-shadcn-ui#127]
Is there a setting to hide the close button in a [Sheet](https://mariuti.com/shadcn-ui/components/sheet/)?

![Screenshot 2024-08-30 at 7 20 21 PM](https://github.com/user-attachments/assets/d437ab31-9581-46e9-9d20-647be6d6ed99)

Basically, I just want to manually manage how Sheet closes.

**Comment by nank1ro** [comment]
closeIcon: SizedBox should work

**Comment by jonsaw** [comment]
Yes, that worked! Thanks for the awesome work
