### ISSUE TITLE
Invoke `onChanged` when selecting same item in `Selector`

### ISSUE THREAD

**Issue by Anas35** [nank1ro/flutter-shadcn-ui#128]
When a user taps the currently selected item again in a `Selector`, the `onChanged` callback is not invoked. [Reference](https://github.com/nank1ro/flutter-shadcn-ui/blob/main/lib/src/components/select.dart#L399-L407)

**Use Cases:** I want to de-select the item, if there select again.

If this too much of breaking change, we may add a flag in selector. Happy to sent a PR.

**Comment by nank1ro** [comment]
It's a great suggestion I haven't thinked about.
It's probably better to add a flag to enable this behavior, something like `enableDeselection` or `allowDeselection` defaulting to false to prevent breaking changes.

Feel free to open a PR, I'll be happy to merge it.

In case add this value to all the stack: Select, Select.withSearch, SelectFormField, SelectTheme and so on, you can copy other fields 👍

**Comment by Anas35** [comment]
On a closer look, it might not possible without changing the `onChanged` generic `T` to nullable generic `T`.
