### ISSUE TITLE
ShadSelect.withSearch full width

### ISSUE THREAD

**Issue by MuhammadAshouri** [nank1ro/flutter-shadcn-ui#129]
### Steps to reproduce

I made a ShadSelect.withSearch widget and wanted to set minWidth to double.infinity to full size it

### Expected results

If I set minWidth to any lower values than double.infinity, such as 300 it works perfectly fine
![image](https://github.com/user-attachments/assets/18b3becc-8a45-4230-9c63-e03492f398be)

### Actual results

But when its set to double.infinity, the options overflows the screen
![image](https://github.com/user-attachments/assets/a1dd25e3-2a8d-4a22-8bc8-e34121784141)

### shadcn_ui version

0.8.1

### Platform

Android

### Code sample

```dart
ShadSelect.withSearch(
  minWidth: 300, // double.infinity
  options: dataList
),
```
(I'm aware that the required params are not here!)

### Flutter Doctor output

<details open><summary>Flutter Doctor output</summary>

[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22635.4145], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\Android\sdk\
    • Platform android-35, build-tools 35.0.0
    • Java binary at: D:\Android\Android studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.11.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at D:\Android\Android studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.92.2)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • sdk gphone16k x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)             • windows       • windows-x64    • Microsoft Windows [Version 10.0.22635.4145]
    • Chrome (web)                  • chrome        • web-javascript • Google Chrome 128.0.6613.86
    • Edge (web)                    • edge          • web-javascript • Microsoft Edge 128.0.2739.42

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by MuhammadAshouri** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

What???

**Comment by nank1ro** [comment]
double.infinity doesn't work because it's an overlay.
An overlay can go beyond the screen.
Try to achieve the result with `MediaQuery.sizeOf(context).width` and removing some padding

**Comment by moshOntong-IT** [comment]
> double.infinity doesn't work because it's an overlay. An overlay can go beyond the screen. Try to achieve the result with `MediaQuery.sizeOf(context).width` and removing some padding

I think layout builder can be help. To make responsive the popover, in my POV

**Comment by MuhammadAshouri** [comment]
> double.infinity doesn't work because it's an overlay. An overlay can go beyond the screen. Try to achieve the result with `MediaQuery.sizeOf(context).width` and removing some padding

Sorry I'm a newbie in flutter... :)
Actually I did that but still not working, I set all paddings to zero and used MediaQuery width
Can you help me with fields that should be filled to do that?
![image](https://github.com/user-attachments/assets/f0880985-757f-4bdb-8155-56adf582087e)

**Comment by moshOntong-IT** [comment]
> > double.infinity doesn't work because it's an overlay. An overlay can go beyond the screen. Try to achieve the result with `MediaQuery.sizeOf(context).width` and removing some padding
> 
> 
> 
> Sorry I'm a newbie in flutter... :)
> 
> Actually I did that but still not working, I set all paddings to zero and used MediaQuery width
> 
> Can you help me with fields that should be filled to do that?
> 
> ![image](https://github.com/user-attachments/assets/f0880985-757f-4bdb-8155-56adf582087e)

how about wrap your shad select with LayoutBuilder? layout builder will give you the constraints of that current widget. AFAIK. The media query width will give you the size of your screen

**Comment by MuhammadAshouri** [comment]
> how about wrap your shad select with LayoutBuilder? layout builder will give you the constraints of that current widget. AFAIK. The media query width will give you the size of your screen

Oh wow, thanks a lot

![image](https://github.com/user-attachments/assets/9c455030-b5c1-4547-94f5-d3e3c7747466)

**Comment by nank1ro** [comment]
@MuhammadAshouri is the issue resolved?

**Comment by jonsaw** [comment]
> > how about wrap your shad select with LayoutBuilder? layout builder will give you the constraints of that current widget. AFAIK. The media query width will give you the size of your screen
> 
> Oh wow, thanks a lot Worked like a charm
> 
> ![image](https://private-user-images.githubusercontent.com/38324227/364366318-9c455030-b5c1-4547-94f5-d3e3c7747466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDQyNDAsIm5iZiI6MTczMTkwMzk0MCwicGF0aCI6Ii8zODMyNDIyNy8zNjQzNjYzMTgtOWM0NTUwMzAtYjVjMS00NTQ3LTk0ZjUtZDNlM2M3NzQ3NDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZjEwNzg5MGFjZjBhZDFjMjExOGEwOWU3NTNkMTIyZTU4ZWJiNWM4ZTlmNzNiNjkwNmZiOTAzMzUzMDc3YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BLO1dxCXwT8wp3MzyH5EQV0TTkBjA7S-2duAMSKKrRM)

The issue with LayoutBuilder is it messes with the tab order for focuses.

https://github.com/user-attachments/assets/f67157a1-dcfd-4c1f-a09c-d0885acaa5f1

**Comment by nank1ro** [comment]
@jonsaw have you tried with
```dart
FocusTraversalGroup(
    policy: OrderedTraversalPolicy(),
    child: ..
)
```
? or `WidgetOrderTraversalPolicy`

**Comment by jonsaw** [comment]
> @jonsaw have you tried with
> 
> ```dart
> FocusTraversalGroup(
>     policy: OrderedTraversalPolicy(),
>     child: ..
> )
> ```
> 
> ? or `WidgetOrderTraversalPolicy`

Yes this works @nank1ro. Thanks for the suggestion!
