### ISSUE TITLE
bug on build after update to 0.9.0

### ISSUE THREAD

**Issue by idan003** [nank1ro/flutter-shadcn-ui#133]
hello,
after i update the shadcn ui to 0.9.0, when i do flutter run i get an error
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/shadcn_ui-0.9.0/lib/src/components/form/form.dart:44:9: Error: Type 'PopInvokedWithResultCallback' not found.

**Comment by nank1ro** [comment]
which flutter version are you using? Did you updated the stable release to 3.24.1?

**Comment by idan003** [comment]
im running 
Flutter (Channel stable, 3.22.2, on macOS 14.6.1 23G93 darwin-x64, locale en-CY)

i will update it and see :)

**Comment by nank1ro** [comment]
lmk

**Comment by idan003** [comment]
working now, thank you very much for all the help :)
