### ISSUE TITLE
Enhancment: Add Bug between Prefix and Placeholder

### ISSUE THREAD

**Issue by moshOntong-IT** [nank1ro/flutter-shadcn-ui#135]
![image](https://github.com/user-attachments/assets/1a1a2fe7-64e1-445d-a797-9232c19e296e)

**Comment by moshOntong-IT** [comment]
Currently, I using this
```
 return ShadInput(
      placeholder: const Text('Search team'),
      prefix: Row(
        children: [
          ShadImage.square(
            size: 16,
            LucideIcons.search,
          ),
          const Gap(16),
        ],
      ),
    );
 ```

**Comment by nank1ro** [comment]
You mean gap not bug right?
Feel free to open a PR yourself

**Comment by moshOntong-IT** [comment]
> You mean gap not bug right? Feel free to open a PR yourself

PR done

[PR](https://github.com/nank1ro/flutter-shadcn-ui/pull/136)

**Comment by nank1ro** [comment]
closed by https://github.com/nank1ro/flutter-shadcn-ui/pull/136
