### ISSUE TITLE
Input copy & paste

### ISSUE THREAD

**Issue by idan003** [nank1ro/flutter-shadcn-ui#139]
hello, 
is there any option to add copy paste to the input?
when i do long press noting is append.

on 
inputTextFiled its working, so maybe there is another way on the ShadInput?

**Comment by moshOntong-IT** [comment]
Same issue

**Comment by moshOntong-IT** [comment]
Waiting for merging https://github.com/nank1ro/flutter-shadcn-ui/pull/142

**Comment by nank1ro** [comment]
implemented in the v0.9.5 by @moshOntong-IT
