### ISSUE TITLE
Table row callback

### ISSUE THREAD

**Issue by renanboni** [nank1ro/flutter-shadcn-ui#143]
hey, there is no callback when clicking on a table row - which seems to be a fairly common use case for a table. Is there a reason for that?

**Comment by nank1ro** [comment]
What's your use case?
I would expect just tap on a cell

**Comment by renanboni** [comment]
I have a list of product and when clicking on the row it should sent to the product detail page.

**Comment by nank1ro** [comment]
Seems feasible, will try a PR in the next days

**Comment by renanboni** [comment]
thanks a lot once again!
