### ISSUE TITLE
ShadSelect.multiple with initialValues leads to duplication

### ISSUE THREAD

**Issue by renanboni** [nank1ro/flutter-shadcn-ui#159]
### Steps to reproduce

1. Create ShadSelect.multiple
2. Pass an array to the initialValues prop
3. Click on any item from the list - the select component will have duplicate values (and you can't unselect them)

### Expected results

The initial values should be considered as "selected" in the dropdown list, unselecting them should remove them from the list.

### Actual results

When clicking on any item from the list, it will be duplicated and it won't be possible to remove it.duplicated

### shadcn_ui version

0.11.0

### Platform

Web

### Code sample

<details open><summary>Code sample</summary>

```dart
ShadSelect<String>.multiple(
          minWidth: 340,
          onChanged: print,
          enabled: enabled,
          focusNode: focusNodes[3],
          allowDeselection: allowDeselection,
          placeholder: const Text('Select multiple fruits'),
          initialValues: ["Apple", "Banana", "Blueberry", "Grapes"],
          closeOnSelect: false,
          options: [
            Padding(
              padding: const EdgeInsets.fromLTRB(32, 6, 6, 6),
              child: Text(
                'Fruits',
                style: theme.textTheme.large,
                textAlign: TextAlign.start,
              ),
            ),
            ...fruits.entries.map(
              (e) => ShadOption(
                value: e.key,
                child: Text(e.value),
              ),
            ),
          ],
          selectedOptionsBuilder: (context, values) =>
              Text(values.map((v) => v.capitalize()).join(', ')),
        ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/cf0e3c5f-4f57-4358-96f9-9f954209ea6d

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by aumb** [comment]
@renanboni 

```dart
initialValues: ["Apple", "Banana", "Blueberry", "Grapes"]
```
should be:
```dart
initialValues: ["apple", "banana", "blueberry", "grapes"]
```
to match the keys in the map defined as such:
```dart
final fruits = {
  'apple': 'Apple',
  'banana': 'Banana',
  'blueberry': 'Blueberry',
  'grapes': 'Grapes',
  'pineapple': 'Pineapple',
};
```

**Comment by renanboni** [comment]
thanks @aumb

**Comment by nank1ro** [comment]
Would add an assert to prevent this 😅
