### ISSUE TITLE
ShadDialog.alert ignores BorderRadius.circular() on android but works on web,linux

### ISSUE THREAD

**Issue by SnoozeFreddo** [nank1ro/flutter-shadcn-ui#165]
### Steps to reproduce

```
1. 

showShadDialog(
      context: context,
      builder: (context) => ShadDialog.alert(
        constraints: BoxConstraints(maxWidth: MediaQuery.sizeOf(context).width * 0.8,),

        radius: BorderRadius.circular(12.0),
        title: const Text('Delete'),
        description: const Padding(
          padding: EdgeInsets.only(bottom: 8),
          child: Text(
            'someText',
          ),
        ),
        actions: [
          ShadButton.outline(
            child: const Text('Cancel'),
            onPressed: () => Navigator.of(context).pop(false),
          ),
          ShadButton.destructive(
            child: const Text('Continue'),

          ),
        ],
      ),
    );
```

### Expected results

Radius should work.

### Actual results

It didn't work. (Corners are at 90°)

### shadcn_ui version

^0.11.1

### Platform

Android

### Code sample

-

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.1 locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/anton/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (7 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/anton/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/anton/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/anton/android-studio/
    • Flutter plugin version 78.2.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/anton/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[!] Android Studio (version unknown)
    • Android Studio at /home/anton/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.93.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by nank1ro** [comment]
This is not a bug, working as intended.
Use `removeBorderRadiusWhenTiny: false` to be able to have the custom radius.
