### ISSUE TITLE
Destructive Toast ShadBorder has no parameter named color as shown in docs

### ISSUE THREAD

**Issue by SnoozeFreddo** [nank1ro/flutter-shadcn-ui#166]
### Steps to reproduce

```
ShadButton.outline(
  child: const Text('Show Toast'),
  onPressed: () {
    ShadToaster.of(context).show(
      ShadToast.destructive(
        title: const Text('Uh oh! Something went wrong'),
        description:
            const Text('There was a problem with your request'),
        action: ShadButton.destructive(
          child: const Text('Try again'),
          decoration: ShadDecoration(
            border: ShadBorder(
              color: theme.colorScheme.destructiveForeground,
            ),
          ),
          onPressed: () => ShadToaster.of(context).hide(),
        ),
      ),
    );
  },
),
```
[Official Docs](https://flutter-shadcn-ui.mariuti.com/components/toast/)

### Expected results

-----

### Actual results

-----

### shadcn_ui version

^0.13.0

### Platform

MacOS, Windows, Linux, Android, iOS, Web

### Code sample

----

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

-

**Comment by nank1ro** [comment]
Will fix the docs, I think with ShadBorder.all it should work
