### ISSUE TITLE
ShadToast closeIcon not showing on android (Works on web / Linux)

### ISSUE THREAD

**Issue by SnoozeFreddo** [nank1ro/flutter-shadcn-ui#167]
### Steps to reproduce

```
final snackBar = ShadToast(
        closeIcon: const Icon(Icons.close, color: Colors.white),
        title: Text('Order deleted successfully.'),
        duration: const Duration(seconds: 5),
      );
      ShadToaster.of(context).show(snackBar);
```

### Expected results

A close button to appear at the top right corner.

### Actual results

No x Icon.

### shadcn_ui version

^0.13.0

### Platform

Android

### Code sample

------

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

------

**Comment by SnoozeFreddo** [comment]
Changing color had no effect.

**Comment by nank1ro** [comment]
Does it work if you use ShadImage with a LucideIcon instead?
Will check your code on Monday

**Comment by nank1ro** [comment]
Not a bug. working as intended.
Use `showCloseIconOnlyWhenHovered: false` to enable it on devices without a mouse. No hover event is triggered on mobile.

**Comment by SnoozeFreddo** [comment]
Aaahhh, i missed that. Thank you.

The Icon is also not touchable on mobile (Doesn't do anything). Is that also intended?
