### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by nank1ro** [nank1ro/flutter-shadcn-ui#17]
https://ui.shadcn.com/docs/components/progress

**Comment by eb-so** [comment]
@nank1ro  I'd like to contribute to the project and start with this component, let me know if you're open to contributions

**Comment by nank1ro** [comment]
Yes @eb-so of course. Thanks 🙏 Just follow the style of other components and don't forget the component theme

**Comment by eb-so** [comment]
@nank1ro Awesome, sure I'll view other component code before I start
