### ISSUE TITLE
ShadSelect.multipleWithSearch failed to set initialValues

### ISSUE THREAD

**Issue by gcanoxl** [nank1ro/flutter-shadcn-ui#173]
### Steps to reproduce

1. create a route page containing a ShadSelect.multipleWithSearch widget.
2. set a simple `initialValues` to it.

### Expected results

After the route page is loaded,
1. the ShadSelect should already be set the `initialValues` provided by the parameter.
2. the `placeholder` argument shouldn't be required, because values are already set.

### Actual results

1. the value hadn't been set
<img width="237" alt="image" src="https://github.com/user-attachments/assets/460514f8-a551-4b3c-97f1-f206a20d1ac9">

2. It occurred an error if the `placeholder` argument hadn't been provided.
<img width="306" alt="image" src="https://github.com/user-attachments/assets/8ea0e38a-812d-45df-af66-ea0979aef78a">

### shadcn_ui version

0.11.0

### Platform

iOS

### Code sample

<details open><summary>Code sample</summary>

```dart
final List<String> countries = [
  "au",
  "en",
  'cn',
];

class TestselectPage extends StatefulWidget {
  const TestselectPage({super.key});
  static const routeName = '/test';

  @override
  State<TestselectPage> createState() => _TestselectPageState();
}

class _TestselectPageState extends State<TestselectPage> {
  String _searchValue = '';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: Center(
        child: ShadSelect<String>.multipleWithSearch(
          initialValues: const ['en'],
          placeholder: const Text('placeholder'),
          options: [
            ...countries.map(
              (e) => ShadOption(
                value: e,
                child: Text(e),
              ),
            )
          ],
          selectedOptionsBuilder: (context, selectedOptions) {
            return Text(selectedOptions.join(', ').toLowerCase());
          },
          onSearchChanged: (value) => setState(() => _searchValue = value),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by nank1ro** [comment]
fixed in the v0.13.5
