### ISSUE TITLE
Setting `scrollBehavior` has no effect 

### ISSUE THREAD

**Issue by dickermoshe** [nank1ro/flutter-shadcn-ui#179]
### Steps to reproduce

1. Set a `scrollBehavior` on `ShadAPp`

### Expected results

Use the `scrollBehavior `

### Actual results

It does not.

### shadcn_ui version

0.14.0

### Platform

MacOS, Windows, Linux, Android, iOS, Web

### Code sample

<details open><summary>Code sample</summary>

Run on desktop!
```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ShadApp.material(
      scrollBehavior: const MaterialScrollBehavior().copyWith(
          dragDevices: {PointerDeviceKind.touch, PointerDeviceKind.mouse}),
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (context, index) => ListTile(title: Text("Item $index")),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

With `ShadApp`:

https://github.com/user-attachments/assets/d5f5c69c-9aa8-41b4-a177-7f69d29aa3c6

With `MaterialApp`:

https://github.com/user-attachments/assets/3bc17fb6-551c-4cf2-804a-2497583bd59d

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2023.1)
[√] VS Code, 64-bit edition (version 1.93.1)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by nank1ro** [comment]
It should be fixed in the v0.14.1
