### ISSUE TITLE
ShadBorder  sides isn't merged

### ISSUE THREAD

**Issue by dickermoshe** [nank1ro/flutter-shadcn-ui#184]
### Steps to reproduce

1. Merge a ShadBorder with another ShadBorder

### Expected results

2. Get a mix of the 2

### Actual results

It's completely replaced!

<img width="554" alt="image" src="https://github.com/user-attachments/assets/c8fd5e15-1368-487f-963a-00dbe777b42e">

ShadBorder sides has a default of BorderSide.none instead of `null`, so a `copyWith` will result in these values getting replaced!

### shadcn_ui version

0.14.1

### Platform

MacOS, Windows, Linux, Android, iOS, Web

### Code sample

<details open><summary>Code sample</summary>

```dart
ShadInput(
placeholder: const Text('Search'),
decoration: ShadDecoration(
    focusedBorder: ShadBorder(
        radius: BorderRadius.circular(16)),
    border: ShadBorder(
        radius: BorderRadius.circular(16))),
)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Why is the border gone

https://github.com/user-attachments/assets/df2bb663-294f-43e0-99c4-698716941bae

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2023.1)
[√] VS Code, 64-bit edition (version 1.93.1)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by nank1ro** [comment]
I was sure that I already addressed this issue. With ShadBorder.all do you have the same issue?

**Comment by dickermoshe** [comment]
This is a broader issue. `merge()` should only override explicitly set properties. So there can't be defaults on themes _anywhere_.
I'm gonna work on a PR which will resolve all of this. The package is littered with many instances of themes with defaults.

**Comment by dickermoshe** [comment]
https://github.com/nank1ro/flutter-shadcn-ui/issues/184
