### ISSUE TITLE
ShadButton: Icon's color is not changing

### ISSUE THREAD

**Issue by HarithHaroon** [nank1ro/flutter-shadcn-ui#213]
### Steps to reproduce

The code to reproduce is provided below.

### Expected results

The icon's color should be red

### Actual results

The icon's color is black. If a primary color is defined, it follows it.

### shadcn_ui version

0.16.3

### Platform

Android

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

void main() {
  runApp(
    const Test(),
  );
}

class Test extends StatelessWidget {
  const Test({super.key});

  @override
  Widget build(BuildContext context) {
    return ShadApp(
      theme: ShadThemeData(
        colorScheme: const ShadSlateColorScheme.light(),
        brightness: Brightness.light,
      ),
      home: const MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: ShadButton.ghost(
          icon: Icon(
            Icons.delete_outlined,
            color: Colors.red,
          ),
          child: Text(
            'Delete',
            style: TextStyle(color: Colors.red),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_1734715425](https://github.com/user-attachments/assets/5af70cfc-cc1a-4c6f-81e8-8037926105e1)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on Ubuntu 24.04.1 LTS 6.8.0-50-generic,
    locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ✗ Android SDK file not found:
      /home/harith/Android/Sdk/platforms/android-35/android.jar.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.95.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 4 categories.

```

</details>

**Comment by nank1ro** [comment]
Oh I got it.
It's because you're overriding the text style and the color.
This is working as expected.
You have two ways to fix this:
1. Set `applyIconColorFilter` to `false`
2. Use `ShadButton.destructive` and don't override the color of the text style

The 2nd one is the preferred way, because the delete action is a destructive operation and all the components that support this operation are styled coherently

**Comment by HarithHaroon** [comment]
Thanks for the response!

I solved it using `applyIconColorFilter: false` since I don't want a background in my destructive button for that part. Played around with `  ShadButton.destructive` but couldn't make it a ghost! 

And while we are here, how can I control the `ShadInputFormField`'s height? or is it something we shouldn't be messing with as design system follows it!
