### ISSUE TITLE
From Google Fonts

### ISSUE THREAD

**Issue by dickermoshe** [nank1ro/flutter-shadcn-ui#48]
Google Fonts & Flutter do not work together nicely at all.
There are a bunch of problems with font weights.
If there is gonna be a func named `fromGoogleFonts`, it would be really nice if it used all the workarounds to get it working correctly out of the box.

Mike Rystrom and Luke Pighetti would know the details.  
I just know that every time I've used `google_fonts` I ran into bugs that the Flutter and Google Fonts team marked as `wont fix`.

**Comment by nank1ro** [comment]
Does these bugs happen even if you download the font locally and add it to the project?
I don't know about which bugs are you referring to, if you have a link to understand better what are the problem would help me a lot

**Comment by dickermoshe** [comment]
https://github.com/material-foundation/flutter-packages/issues/141
https://github.com/material-foundation/flutter-packages/issues/35

**Comment by dickermoshe** [comment]
No, they're due to the way google_fonts works

**Comment by dickermoshe** [comment]
https://github.com/material-foundation/flutter-packages/issues/35#issuecomment-1954054725

**Comment by dickermoshe** [comment]
If this is something the package can't handle, then adding docs for the func would be best.
If a function is named `fromGoogleFonts` you would expect everything to work perfectly

**Comment by nank1ro** [comment]
what a strange bug, and the fact that this issue is open since 2019 it's even worse.
[This one](https://github.com/material-foundation/flutter-packages/issues/35#issuecomment-605353195) seems the only workaround properly working, would check out.
I don't know if I can really integrate here, would try now.

**Comment by dickermoshe** [comment]
Shorter syntax:

**Comment by nank1ro** [comment]
Thanks for the sharing. I think I made it working.
<img width="171" alt="Screenshot 2024-03-24 at 17 12 49" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/60045235/69ca1270-5354-4e75-8372-52a0cafb51b3">
Will release an update soon

**Comment by dickermoshe** [comment]
Thanks so much. Solid improvement.
