### ISSUE TITLE
Placeholder ShadInputFormField look like not centered

### ISSUE THREAD

**Issue by hifiaz** [nank1ro/flutter-shadcn-ui#50]
i use setup

```
    ShadApp.materialRouter(
      debugShowCheckedModeBanner: false,
      title: 'Feel Better',
      routerConfig: _router,
    );
```

but when use input placeholder look like not centered on vertical

```
       ShadInputFormField(
          id: 'name',
          label: const Text('What Happened'),
          placeholder: const Text('Meet My Dad'),
          controller: editingName,
          validator: (v) {
            if (v.length < 2) {
              return 'must be at least 2 characters.';
            }
            return null;
          },
        ),
```
<img width="277" alt="Screenshot 2024-04-03 at 06 09 24" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/20653803/93abfee2-9023-4714-8721-d1dc45c0cc66">
<img width="271" alt="Screenshot 2024-04-03 at 06 09 17" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/20653803/4b3a50cc-0be6-4d8a-9881-ab4d3a11a243">

**Comment by nank1ro** [comment]
Can you add a screenshot with something written instead?
To see how the normal text aligns

**Comment by hifiaz** [comment]
@nank1ro you mean like this?
<img width="140" alt="Screenshot 2024-04-03 at 12 48 16" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/20653803/edcffffa-b4c9-4ec8-950a-bc9f37bbb4d1">

**Comment by hifiaz** [comment]
@nank1ro i use macos emulator to run it

**Comment by nank1ro** [comment]
Hi @hifiaz
I created a PR where I made some changes. I haven't reproduced the issue, but I'd like to check if the PR solves the problem you're facing.
Can you try the branch and see if it works? Update the `pubspec.yaml` shadcn_ui dependency with this one:
```yaml
shadcn_ui:
    git:
      url: https://github.com/nank1ro/flutter-shadcn-ui
      ref: fix/input-placeholder-alignment
```
<img width="387" alt="Screenshot 2024-04-04 at 11 52 24" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/60045235/72a316f5-4364-4599-b4cb-d6514df60817">

**Comment by hifiaz** [comment]
@nank1ro looks good, but other issue, when i set maxlines ex: 5 hint not on start, any option to make it on left top?
<img width="289" alt="Screenshot 2024-04-04 at 20 33 26" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/20653803/7d488729-ad0d-4e5e-9ec8-a3a2590266db">

**Comment by nank1ro** [comment]
Can you try the latest update? `flutter pub upgrade shadcn_ui` should be enough.
I added again the padding, so your initial issue may appear again.
Let me know, in case you still see the issue, please share the code, in particular if you have points in the app were you change the decoration theme, or the input decoration.
Give me also the output of `flutter doctor -v`

**Comment by hifiaz** [comment]
yes look like current issue appear again, but all good for now

**Comment by nank1ro** [comment]
Try putting the text "Meet my dad" in the placeholder, then try writing it the same, does the position change or is it the same?
If you can make a video it would help.

Give me also the output of `flutter doctor -v` because I'm not able to reproduce your issue.

**Comment by Dredayduncan** [comment]
I also had a similar issue. I noticed it only occurs when you specify the placeholder without an InputDecoration with a specified placeholderStyle.

**Comment by Dredayduncan** [comment]
`ShadInputFormField(
      placeholder: Text('Placeholder'),
    );`
    
I noticed it also shows on the Form preview example on the documentation website. It's minute but the placeholder is closer to the bottom of the input field.

**Comment by nank1ro** [comment]
> `ShadInputFormField( placeholder: Text('Placeholder'), );`
> 
> I noticed it also shows on the Form preview example on the documentation website. It's minute but the placeholder is closer to the bottom of the input field.

<img width="385" alt="Screenshot 2024-05-08 at 16 56 56" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/60045235/06f17146-422a-49e0-a0a0-859b188fc74e">

I still can't notice the problem, however you can easily change the position of the text and placeholder changing the padding, for example:
```dart
ShadInputFormField(
 padding: const EdgeInsets.only(
  top: 8,
  left: 12,
  right: 12,
  bottom: 9, // or whatever value you want
 ),
),
```

**Comment by nank1ro** [comment]
I probably figured out what you meant.
I updated the baseline of the text styles and now the text looks more centered.
<img width="444" alt="Screenshot 2024-05-09 at 11 25 08" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/60045235/5f569b0b-1715-4148-b28f-5b2f752c8cc4">

Consider opening a new issue if you experience again the same problem
