### ISSUE TITLE
Input OTP

### ISSUE THREAD

**Issue by louis-sicko** [nank1ro/flutter-shadcn-ui#58]
https://ui.shadcn.com/docs/components/input-otp

**Comment by nank1ro** [comment]
Thanks for the reasoning. I don't think I will work soon to this component. The missing ones are more important and probably more needed.
Don't know if you wanna try yourself implementing it, can give suggestions if needed

**Comment by moshOntong-IT** [comment]
I need this too, usually India and Philippines likey have Phone Number authentication. This is good if we have this

**Comment by moshOntong-IT** [comment]
> Thanks for the reasoning. I don't think I will work soon to this component. The missing ones are more important and probably more needed. Don't know if you wanna try yourself implementing it, can give suggestions if needed

Want to ask, what could be the `missing ones` ?
