### ISSUE TITLE
Search field for Select component

### ISSUE THREAD

**Issue by komiljonovshohjahon** [nank1ro/flutter-shadcn-ui#68]
### Steps to reproduce

Hi
I was wondering if you could add a functionality to filter options in the Select component.
It is very handy for Desktop and Web apps.

### Expected results

![Screenshot 2024-05-20 at 16 36 43](https://github.com/nank1ro/flutter-shadcn-ui/assets/74962465/6fa9b5ab-cd90-40a6-9fc4-550272a1bf04)

### Actual results

![Screenshot 2024-05-20 at 16 36 43](https://github.com/nank1ro/flutter-shadcn-ui/assets/74962465/6fa9b5ab-cd90-40a6-9fc4-550272a1bf04)

### Platform

MacOS, Windows, Linux, Android, iOS, Web

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by nank1ro** [comment]
There is the ComboBox widget.
https://ui.shadcn.com/docs/components/combobox
Already added to the README as a todo

**Comment by komiljonovshohjahon** [comment]
Currently added like so inside options as a widget.

<img width="665" alt="Screenshot 2024-05-20 at 16 41 15" src="https://github.com/nank1ro/flutter-shadcn-ui/assets/74962465/b2526848-e5cc-46b8-8cc6-0354ffcca444">

**Comment by komiljonovshohjahon** [comment]
> There is the ComboBox widget. https://ui.shadcn.com/docs/components/combobox Already added to the README as a todo

Are you working on this already, or have not started yet?

**Comment by nank1ro** [comment]
> > There is the ComboBox widget. https://ui.shadcn.com/docs/components/combobox Already added to the README as a todo
> 
> 
> 
> Are you working on this already, or have not started yet?

Not started yet
