### ISSUE TITLE
Feedback animation  response is very slow 

### ISSUE THREAD

**Issue by santoshgistto** [nank1ro/flutter-shadcn-ui#73]
### Steps to reproduce

1. Select any field like popover

### Expected results

response should be quick 

### Actual results

Animation feedback response  is slow 

### Platform

Web

### Code sample

final fruits = {
 'apple': 'Apple',
 'banana': 'Banana',
 'blueberry': 'Blueberry',
 'grapes': 'Grapes',
 'pineapple': 'Pineapple',
};

@override
Widget build(BuildContext context) {
 return ConstrainedBox(
   constraints: const BoxConstraints(minWidth: 180),
   child: ShadSelect<String>(
     placeholder: const Text('Select a fruit'),
     options: [
       Padding(
         padding: const EdgeInsets.fromLTRB(32, 6, 6, 6),
         child: Text(
           'Fruits',
           style: theme.textTheme.muted.copyWith(
             fontWeight: FontWeight.w600,
             color: theme.colorScheme.popoverForeground,
           ),
           textAlign: TextAlign.start,
         ),
       ),
       ...fruits.entries
           .map((e) =>
               ShadOption(value: e.key, child: Text(e.value)))
           .toList(),
     ],
     selectedOptionBuilder: (context, value) =>
         Text(fruits[value]!),
   ),
 );
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by nank1ro** [comment]
@santoshgistto what do you mean with animation feedback?
