### ISSUE TITLE
Popover doesn't track anchor during window resize

### ISSUE THREAD

**Issue by lukepighetti** [nank1ro/flutter-shadcn-ui#82]
### Steps to reproduce

1. open popover on macOS (didn't try other platforms)
2. resize window

### Expected results

1. popover tracks the anchor

### Actual results

https://github.com/nank1ro/flutter-shadcn-ui/assets/666539/638821ca-60e7-4117-968a-2c7ef708ae9f

### Platform

MacOS

### Code sample

x

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.

**Comment by nank1ro** [comment]
Thanks for filling the issue, are you using the popover component directly or the select?

**Comment by nank1ro** [comment]
In the select component the anchor is fixed
```dart
        const ShadAnchor(
          childAlignment: Alignment.bottomLeft,
          overlayAlignment: Alignment.topLeft,
          offset: Offset.zero,
        );
```
Even if you resize the window the position is keeped.

In the popover the anchor used is:
```dart
        const ShadAnchorAuto(
          verticalOffset: 24,
          preferBelow: true,
        );
```
This anchor will move the overlay to keep it visible in the screen.

**Comment by nank1ro** [comment]
Do you want this behavior?

https://github.com/nank1ro/flutter-shadcn-ui/assets/60045235/64fb09e5-287c-4752-9c8b-41f73296ca3a

**Comment by nank1ro** [comment]
In the latest version I set this as the default behavior.
You can revert back to the back behavior setting `followTargetOnResize` to false in the `ShadAnchorAuto` class, if you don't like it.
