### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by Aadii-shah** [nank1ro/flutter-shadcn-ui#84]
### Steps to reproduce

1.Create a Flutter project.
2.Add the shadcn_ui package version 0.5.4 to your pubspec.yaml.
3.Use the following code in your project to implement a ShadSelect widget:
final fruits = {
 'apple': 'Apple',
 'banana': 'Banana',
 'blueberry': 'Blueberry',
 'grapes': 'Grapes',
 'pineapple': 'Pineapple',
};

@override
Widget build(BuildContext context) {
 return ConstrainedBox(
   constraints: const BoxConstraints(minWidth: 180),
   child: ShadSelect<String>(
     placeholder: const Text('Select a fruit'),
     options: [
       Padding(
         padding: const EdgeInsets.fromLTRB(32, 6, 6, 6),
         child: Text(
           'Fruits',
           style: theme.textTheme.muted.copyWith(
             fontWeight: FontWeight.w600,
             color: theme.colorScheme.popoverForeground,
           ),
           textAlign: TextAlign.start,
         ),
       ),
       ...fruits.entries
           .map((e) =>
               ShadOption(value: e.key, child: Text(e.value)))
           .toList(),
     ],
     selectedOptionBuilder: (context, value) =>
         Text(fruits[value]!),
   ),
 );
}

### Expected results

The ShadSelect widget should display a dropdown menu with the list of fruits and allow the user to select an option without any errors.

### Actual results

'ShadInputState' is from 'package:shadcn_ui/src/components/input.dart' ('../../../.pub-cache/hosted/pub.dev/shadcn_ui-0.5.4/lib/src/components/input.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateMouseCursor'.
        widget.mouseCursor ?? WidgetStateMouseCursor.textable;
                              ^^^^^^^^^^^^^^^^^^^^^^

### Platform

iOS

### Code sample

<details open><summary>Code sample</summary>

```dart
[final fruits = {
 'apple': 'Apple',
 'banana': 'Banana',
 'blueberry': 'Blueberry',
 'grapes': 'Grapes',
 'pineapple': 'Pineapple',
};

@override
Widget build(BuildContext context) {
 return ConstrainedBox(
   constraints: const BoxConstraints(minWidth: 180),
   child: ShadSelect<String>(
     placeholder: const Text('Select a fruit'),
     options: [
       Padding(
         padding: const EdgeInsets.fromLTRB(32, 6, 6, 6),
         child: Text(
           'Fruits',
           style: theme.textTheme.muted.copyWith(
             fontWeight: FontWeight.w600,
             color: theme.colorScheme.popoverForeground,
           ),
           textAlign: TextAlign.start,
         ),
       ),
       ...fruits.entries
           .map((e) =>
               ShadOption(value: e.key, child: Text(e.value)))
           .toList(),
     ],
     selectedOptionBuilder: (context, value) =>
         Text(fruits[value]!),
   ),
 );
}]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
['ShadInputState' is from 'package:shadcn_ui/src/components/input.dart' ('../../../.pub-cache/hosted/pub.dev/shadcn_ui-0.5.4/lib/src/components/input.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateMouseCursor'.
        widget.mouseCursor ?? WidgetStateMouseCursor.textable;
                              ^^^^^^^^^^^^^^^^^^^^^^]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
    • Flutter version 3.19.6 on channel stable at /Users/slab/Developer/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (2 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/slab/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • B8DBADE3-5A76-4B19-9278-966E290A1784 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 126.0.6478.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!]
```

</details>

**Comment by ArunKashyapp** [comment]
^0.2.4 working fine with this version but yeah latest version is not working

**Comment by nank1ro** [comment]
I know this error, you just need to update flutter to the latest stable

**Comment by nank1ro** [comment]
I'm not referring to the version of the library, but your Flutter version.
Please run `flutter upgrade` in the terminal

**Comment by Aadii-shah** [comment]
Thanks for the tip!
