### ISSUE TITLE
Input Form Field's Label doesn't resolved style with theme's Label Style

### ISSUE THREAD

**Issue by Anas35** [nank1ro/flutter-shadcn-ui#90]
### Steps to reproduce

1. Define label style in `ShadInputTheme` in `ShadThemeData`

```dart
inputTheme: const ShadInputTheme(
  decoration: ShadDecoration(
    labelStyle: TextStyle(
      color: Colors.red,
      fontSize: 18,
      fontWeight: FontWeight.w600,
      height: 28 / 18,
    ),
  ),
),
```
2. Define a Shad Form Field

```dart
 ShadInputFormField(
    label: const Text('Label Text'),
),
```
3. Label Style doesn't get resolve from theme, but rather with default label style.

### Expected results

![Screenshot 2024-07-07 173605](https://github.com/nank1ro/flutter-shadcn-ui/assets/65850618/7c2e53dc-2dd5-4c8c-bdfa-85f3da0e032c)

### Actual results

![Screenshot 2024-07-07 173640](https://github.com/nank1ro/flutter-shadcn-ui/assets/65850618/bc99ca22-dfcc-4f5b-98e5-cbe3c2599c9e)

**Comment by nank1ro** [comment]
Thanks for the report!
Can you try the following branch changing the pubspec.yaml to see if it resolves the issue?
```yaml
shadcn_ui:
    git:
      url: https://github.com/nank1ro/flutter-shadcn-ui
      ref: fix/decoration
```

**Comment by Anas35** [comment]
working perfectly! Thank you for quick fix.
