### ISSUE TITLE
Request to Add GetX Support

### ISSUE THREAD

**Issue by Digvijaysinh2204** [nank1ro/flutter-shadcn-ui#91]
I would like to propose adding support for GetX state management in the Shadcn UI framework. GetX is widely used in the Flutter ecosystem for its simplicity and performance in handling state and dependencies. Integrating GetX with Shadcn UI would greatly benefit developers by providing a robust and efficient way to manage state within the UI components.

**Comment by nank1ro** [comment]
It will not happen.
I have already said why in [this discussion ](https://github.com/nank1ro/flutter-shadcn-ui/discussions/63)
If you really want to do that, you can fork the library and edit the app.dart file following the cupertino implementation.
