### ISSUE TITLE
Support for animation duration property

### ISSUE THREAD

**Issue by LouisLou2** [nank1ro/flutter-shadcn-ui#93]
### Steps to reproduce

I'm using ShadSelect widget but i found that it is not equipped with animation duration property and the default fadeIn animation looks a bit slow. I dont know how to specify it.

### Expected results

.

### Actual results

.

### Platform

MacOS, Windows, Linux, Android, iOS, Web

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
.

**Comment by nank1ro** [comment]
This is a bug, I haven't exposed the effects to allow their customization.
