### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by moshOntong-IT** [nank1ro/flutter-shadcn-ui#96]
### Steps to reproduce

1. Read the Documentation of ShadPopover Section
2. You can see here that it has `builder` property within ShadPopover

### Expected results

The `builder` is deprecated it is now `popover`

### Actual results

The documentation still displaying the `builder`

### Platform

Windows

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by nank1ro** [comment]
fixed, thanks 👍
