### ISSUE TITLE
FEATURE: Google Font from ShadTheme must also be feed to the Material Theme

### ISSUE THREAD

**Issue by moshOntong-IT** [nank1ro/flutter-shadcn-ui#98]
When we are not using the Material Theme by using these `ShadApp` or `ShadApp.router`, and we are configuring the ShadTheme in instance inserting the Google Font in ShadTheme, so it must be automatic feed to the Material Theme.

**Comment by nank1ro** [comment]
I already solved it in the following issue https://github.com/nank1ro/flutter-shadcn-ui/issues/87
Are you using the latest version of shadcn_ui? (v0.6.3)

**Comment by moshOntong-IT** [comment]
> I already solved it in the following issue #87 Are you using the latest version of shadcn_ui? (v0.6.3)

Ohh I see I will check
